get_grid_profiles:
set_grid_profile:
  fields:
    profile:
      required: true
      example: "EN 50549-1:2019 RfG E02 Netherlands:1.2.4"
      selector:
        text:
upload_grid_profile:
  fields:
    file:
      required: true
      example: "/share/grid_profiles/64d31e5868ac391817b21af1"
      selector:
        text:
get_api_key:
  description: "Fetch the current short-lived API key from Enphase Envoy"


